### PR TITLE
Make routes optional

### PR DESCRIPTION
**Pull request by emiliopedrollo**
Honestly I don't think it makes sense on a package like that to define routes. Maybe I'm just misunderstanding what this project is supposed to be.

Relates to #16.

### CODE REVIEW

**Comment by nnjeim** [comment]
@emiliopedrollo Hi and thank you for your contribution. The package can be used as an api or consumed via the world facade. This is the reason why the routes are defined. I will pull this route and test your proposed modification.
Thank you

**Comment by nnjeim** [comment]
@emiliopedrollo 
in world.php config files you can find the seeders key:
```
*/
	'seeders' => [
		'states' => true,
		'cities' => true,
		'timezones' => true,
		'currencies' => true,
		'languages' => true,
	],
```
What do you think if routes and seeder keys are combined into :
```
'modules' => true,
		'cities' => true,
		'timezones' => true,
		'currencies' => true,
		'languages' => true,
```

**Comment by nnjeim** [comment]
@emiliopedrollo Thank you for this. I would opt to keep things simple in a config file if you agree with this approach.

**Review by nnjeim — APPROVED** [review]

**Comment by nnjeim** [comment]
@emiliopedrollo thank you, i am merging the PR.

**Comment by kodjosama** [comment]
@emiliopedrollo Thanks dude, that's awesome. I was hoping to implement this feature when I got time. Thanks  @nnjeim for this package.

**Comment by nnjeim** [comment]
@kodjosama Thank you. All the credit goes to @emiliopedrollo

**Pull request merged**
